ZL8以上の都市名、町名、村名の表示順序、フォント設定、パディングの変更
geoloniamaps/basic pull request #143
Opened 2022-03-04 17:33 UTC by ShinichiNishikawa

こちらを実施しました。

https://github.com/geoloniamaps/basic/issues/142

2022-03-04 17:36 UTC, ShinichiNishikawa commented
テスト落ちてしまいました。

@naogify  この辺、今度教えてください。

2022-03-04 23:07 UTC, naogify requested changes

2022-03-04 23:07 UTC, naogify commented on style.yml
>    - !!inc/file layers/place-city-rank3.yml
@ShinichiNishikawa 
`- !!inc/file layers/place-city-rank3.yml` が削除されていたのに、`style.yml` で読み込んでいるのがエラーの原因でした。

2022-03-07 05:24 UTC, ShinichiNishikawa commented on style.yml
>    - !!inc/file layers/place-city-rank3.yml
修正しました。

2022-03-23 07:51 UTC, closed without merging