add style render time watcher
geoloniamaps/basic pull request #268
Opened 2022-08-08 07:18 UTC by naogify

2022-08-12 07:26 UTC, keichan34 requested changes
諸々確認お願いします :bow:

2022-08-12 07:26 UTC, keichan34 commented on bin/style-render-time.js
> +    const zoomList = [ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20 ]
z20までだとコメントが結構大きくなってしまうので、主要の3つ？4つ？5つ？ぐらいに絞りましょうか。一番使われそうなズームで。

2022-08-12 07:26 UTC, keichan34 commented on package.json
> +    "http": "^0.0.1-security",
`http` は nodejs の標準ライブラリに含まれているので、npmで入れる必要ありません

2022-08-12 07:26 UTC, keichan34 commented on docs/index.html
> +      mapRenderedTime = performance.getEntriesByType('measure')[0].duration;
3つのperformance.mark/measureってなんで使ってるんですか？1つでいけるかと思うけど、何か理由があって 'map-render-time', 'map-render-start', 'map-render-end' に分けているのかな。それにしても getEntriesByType 使っているのでもし他の場所で使っているなら不正確な情報が来るのかな？（ `getEntriesByName` か直接 `measure` の戻り値を使えばいいと思いました。。。）

2022-08-12 07:26 UTC, keichan34 commented on package.json
> +    "test:e2e": "node ./bin/style-render-time.js"
`test:render-time` か `benchmark:render-time` の方が適切かな。特にテストを走らせているわけでもないし、 end-to-end テストって言われるとその間に何か壊れているとキャッチできる様なニュアンスだから違うのかな。。

2022-08-12 08:44 UTC, naogify commented on bin/style-render-time.js
> +    const zoomList = [ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20 ]
確かにですね。こちら よく使われそうなズームレベル z5、7、11、14 に絞りました!

2022-08-12 08:44 UTC, naogify commented on package.json
> +    "http": "^0.0.1-security",
ありがとうございます。修正しました!

2022-08-12 08:51 UTC, naogify commented on docs/index.html
> +      mapRenderedTime = performance.getEntriesByType('measure')[0].duration;
ありがとうございます! こちら `measure` の戻り値を使うように修正しました。
https://github.com/geoloniamaps/basic/blob/96bae279fa4553a97a80f757ba537d2fa614147f/docs/index.html#L67

2022-08-12 08:52 UTC, naogify commented on package.json
> +    "test:e2e": "node ./bin/style-render-time.js"
確かに、e2e ではないですね。修正しました!

2022-08-15 01:57 UTC, keichan34 approved these changes
ありがとうございます！
いつかこれを汎用化して他のスタイルレポジトリーに簡単に埋め込められるようにしたい。。

2022-08-15 07:02 UTC, naogify commented
@keichan34 
ありがとうございます! 

> いつかこれを汎用化して他のスタイルレポジトリーに簡単に埋め込められるようにしたい。。

そうですね、手始めにこれと同じものを GSI にも追加しようと思います。

2022-08-15 07:03 UTC, merged