路線名を表示
geoloniamaps/basic pull request #53
Opened 2021-09-08 03:13 UTC by naogify

2021-09-08 03:25 UTC, naogify commented
- [ ] 線路に沿って路線名を表示
- [ ] 路線名を表示する間隔を空ける

2021-09-13 23:31 UTC, kamataryo approved these changes

2021-09-14 00:07 UTC, keichan34 requested changes
基本的に良いと思いますがv2デプロイしてからapproveします :bow:

2021-09-14 02:07 UTC, keichan34 commented
@naogify v2 リリースしましたのであとほどそちらで確認お願いします! :bow:

2021-09-14 02:43 UTC, naogify commented
@keichan34 
ありがとうございます！v2 に変更します。

2021-09-14 03:10 UTC, naogify commented
@keichan34 @kamataryo 

こちらv2に変更しました! 確認しましたが特におかしくなっている点はないようです。

2021-09-15 01:30 UTC, merged